# Generated by Django 5.0.14 on 2026-09-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomiaIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('energia_sem_iot', models.FloatField()),
                ('energia_com_iot', models.FloatField()),
                ('manutencao_sem_iot', models.FloatField()),
                ('manutencao_com_iot', models.FloatField()),
                ('paradas_sem_iot', models.FloatField()),
                ('paradas_com_iot', models.FloatField()),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
